image:
  file: .gitpod.dockerfile
tasks:
 - init: . ${GITPOD_REPO_ROOT}/.theia/init_tasks.sh    
vscode:
  extensions:
    - ms-python.python@2019.8.30787:TnGEOx35GXMhyKLjDGz9Aw==
    - mkaufman.HTMLHint@0.6.0:TdNYbCmjW8N3yiaPW4/adg==
    - eventyret.bootstrap-4-cdn-snippet@1.3.0:3EJTfpRZ7YoP6Ty3NIdt5Q==